### ISSUE TITLE
Create a live web site like HectorArellano.github.com/PBF_GPU?

### ISSUE THREAD

**Issue by oscarbg** [HectorArellano/PBF_GPU#2]
so we don't have to download and create a localhost webserver..
thanks.

**Comment by HectorArellano** [comment]
Hi! this uses web based technology, but I'm not planning on setting a live version since the rendering time is quite slow on almost all the machines. Actually the only thing that I would advise to use for production is the PBF simulator (and take into account that uses webGL2). You'll have to work with a low level of particles, or modify the shaders to have any type or resolution (right now the shaders only accept power of 2 resolutions for debugging).

Once I finish the color compression/blending in the potential generation I might start working on performance to have a live version. This new version won't use the raytracer since the fluid won't be transparent (might be only use fresnel and a simple phong shading), that would make it run at a decent frame rate depending on the resolution for the simulation and the surface.
